language: r
warnings_are_errors: false
sudo: required

notifications:
  email:
    recipients:
      - nicolas.casajus@fondationbiodiversite.fr

r_packages:
  - rvest

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
