language: r
warnings_are_errors: false
sudo: required
cache: packages

notifications:
  email:
    recipients:
      - nicolas.casajus@fondationbiodiversite.fr

r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'covr::codecov()'

before_install:
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
